
CREATE TABLE IF NOT EXISTS notes (
  node_id BIGSERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS note_details (
  id BIGSERIAL PRIMARY KEY,
  note_id BIGINT NOT NULL REFERENCES notes(node_id) ON DELETE CASCADE,
  detail_key VARCHAR(100) NOT NULL,
  detail_value TEXT NOT NULL,
  sensitive BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS  idx_note_details_note_id ON note_details(note_id);
